# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66061033e806643e7077908634f15e9807e6c4b738de474f382030e9096965e0551c7b2485a5189fa19f5fedc87acc9f98ec0b4e82401ae1d67766f0798f2fd0

test:
  secret_key_base: 0f4fa6dd90657964fb79bc32595b53b8ac3500f44cfc11c89bb828c4f5edc76ab0e40776e8f63288a1bae1a2d7e3f708c2e277e0910fcb364bfd0753d7bc1c59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
